@startuml
'https://plantuml.com/sequence-diagram

start
:判断是否重复关闭连接;
:确定关闭连接的线程和创建连接的线程是不是一个;
if (是同一个线程) then (执行同步关闭连接)
    :同步关闭链接;
else (异步关闭连接)
note left
这里 a 线程创建的链接 被 b 线程关闭,
可能此时 a 还在使用链接 ,所以这里要做同步处理
end note
endif
:执行链接关闭过滤器;
partition "回收链接逻辑" {
    :判断是不是创建连接的线程,不是的话打印 warn 日志;
    :将其从存活链接中移除;
    :检测是否设置了自动提交,设置了的话,回滚事务;
    :如果不是同一线程,重新设置连接 hold 的配置;
    :把回收的连接放在连接池尾部;
    :放失败了关闭连接;
}
end
@enduml